#:kivy 1.9.0
#:import sys sys
#:import lv kivy.uix.listview
#:import la kivy.adapters.listadapter
#:import os os


#---------------------------------------------------#
# Item listview
[CustomListItem@SelectableView+BoxLayout]:
    cbLayout: cb_layout
    size_hint_y: None
    BoxLayout:
        id: item_id
        orientation: "vertical"
        size_hint_y: None
        # canvas.before:
        #     Color:
        #         rgba: 0, 0.94, 0.94, 1
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size
        BoxLayout:
            size_hint: 1, None
            height: 40
            BoxLayout:
                size_hint_x: 1.5
                padding: 10, 0, 0, 0
                Label:
                    text_size: self.width, None
                    color: 0,0,0,1
                    font_size: '16sp'            
                    text: ctx.text
            
            Button:
                size_hint_x: 0.5
                background_color: 1, 1, 1, 0
                on_press: ctx.remove_item(ctx.item_id, ctx.list_id)
                Image:
                    source: 'img/remove.png'
                    size: 20, 20
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                    allow_stretch: True

        BoxLayout:
            id: cb_layout
            orientation: "vertical"
            size_hint_y: None
            height: 50

        BoxLayout:
            size_hint_y: None
            height: 1
            canvas.before:
                Color:
                    rgba: 0.92, 0.92, 0.92, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

<ItemCheckBox>:
    chainName: chain_name
    spacing: 20
    CheckBox:
        size_hint_x: None
        width: 50
        active: True
    Label:
        id: chain_name
        text: ''
        color: 0,0,0,1
        font_size: '14sp'
        text_size: self.width, None
        halign: 'left'

#---------------------------------------------------#
# Screen

<AnotherScreen>:
    Button:
        on_release: app.root.current = 'load'
        text: 'back to the home screen'
        font_size: 50


<SettingScreen>:
    canvas.before:
        Color:
            rgba: 0.92, 0.92, 0.92, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size
    FloatLayout:
    Label:
        text: 'Settings'
        font_size: 50
        color: 0,0,0,1
    Button:
        background_color: 1, 1, 1, 0
        size_hint: None, None
        size: 50, 50
        pos: 50, 30
        on_press: root.manager.current = 'load'
        Image:
            source: 'img/back.png'
            size: 50, 50
            center_x: self.parent.center_x
            center_y: self.parent.center_y
            allow_stretch: True

<LoadScreen>:
    boxlist_1: box_list_1    
    boxlist_2: box_list_2

    canvas.before:
        Color:
            rgba: 0.92, 0.92, 0.92, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size

    FloatLayout:
        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-100, 30
            on_press: root.manager.current = 'another'
            Image:
                source: 'img/next.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: 50, 30
            on_press: root.manager.current = 'setting'
            Image:
                source: 'img/setting.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        BoxLayout:
            id: box_load
            size_hint: None, None
            size: root.width * 9/10, root.height * 6/10
            pos: root.width /20, root.height * 2/10
            spacing: 20
            BoxLayout:
                id: box_load_1
                orientation: "vertical"
                spacing: 10
                Button:
                    background_color: 0, 0.588, 0.533, 1
                    background_normal: ''
                    text: 'Add Receptor'
                    size_hint: None, None
                    size: box_load_1.width, 30
                    on_release: root.show_load_receptor()
                BoxLayout:
                    id: box_list_1
                    size: box_load_1.width, box_load_1.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.92, 0.92, 0.92
                        Line:
                            rectangle: self.x,self.y,self.width,self.height
                    # ListView:
                    #     id: pdb_list_1
                    #     adapter:
                    #         la.ListAdapter(data=[], template='CustomListItem')

            BoxLayout:
                id: box_load_2
                orientation: "vertical"
                spacing: 10
                Button:
                    background_color: 0, 0.588, 0.533, 1
                    background_normal: ''
                    text: 'Add Ligand'
                    size_hint: None, None
                    size: box_load_2.width, 30
                    on_release: root.show_load_ligand()
                BoxLayout:
                    id: box_list_2
                    size: box_load_1.width, box_load_1.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.92, 0.92, 0.92
                        Line:
                            rectangle: self.x,self.y,self.width,self.height

#---------------------------------------------------#
# Dialog
<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            path: os.getcwd()
            multiselect: True

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
