#---------------------------------------------------#
# Item listview
[LoadListItem@SelectableView+BoxLayout]:
    cbLayout: cb_layout
    size_hint_y: None
    height: 40 + 30*len(ctx.pdbFile.chains) + 1
    BoxLayout:
        id: item_id
        orientation: "vertical"
        size_hint_y: None
        height: 40 + 30*len(ctx.pdbFile.chains) + 1
        # canvas.before:
        #     Color:
        #         rgba: 0, 0.94, 0.94, 1
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size
        BoxLayout:
            size_hint: 1, None
            height: 40
            FloatLayout:
                size_hint_x: None
                width: 30
                padding: 10, 0, 0, 0
                Image:
                    source: ctx.root_path +'/img/file.png'
                    size: 20, 20
                    allow_stretch: True
                    size_hint: None, None
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y

            BoxLayout:
                size_hint_x: 1.5
                Label:
                    text_size: self.width, None
                    color: 0,0,0,1
                    font_size: '16sp'            
                    text: ctx.text
                    valign: 'middle'
            
            Button:
                size_hint_x: 0.5
                background_color: 1, 1, 1, 0
                on_press: ctx.remove_item(ctx.item_id, ctx.list_id, ctx.pdbFile)
                Image:
                    source: ctx.root_path +'/img/remove.png'
                    size: 20, 20
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                    allow_stretch: True

        BoxLayout:
            id: cb_layout
            orientation: "vertical"
            # size_hint_y: None
            # height: 50

        BoxLayout:
            size_hint_y: None
            height: 1
            canvas.before:
                Color:
                    rgba: 0.92, 0.92, 0.92, 1
                Rectangle:
                    pos: self.pos
                    size: self.size


<ItemCheckBox>:
    chainName: chain_name
    chainBox: chain_box
    spacing: 20
    size_hint_y: None
    height: 30
    CheckBox:
        id: chain_box
        size_hint_x: None
        width: 50
        active: True
    Label:
        id: chain_name
        text: ''
        color: 0,0,0,1
        font_size: '14sp'
        text_size: self.width, None
        halign: 'left'

<LoadScreen>:
    boxlist_1: box_list_1    
    boxlist_2: box_list_2

    canvas.before:
        Color:
            rgba: 0.92, 0.92, 0.92, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size

    FloatLayout:
        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-100, 30
            on_press: root.manager.changeScreen('receptor')
            Image:
                source: root.root_path +'/img/next.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: 50, 30
            on_press: root.manager.changeScreen('setting')
            Image:
                source: root.root_path +'/img/setting.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        BoxLayout:
            size_hint: None, None
            size: root.width * 9/10, root.height * 2/10
            pos: root.width /20, root.height * 8/10
            canvas.before:
                Color:
                    rgba: 0.62, 0.62, 0.62, 1
                Rectangle:
                    pos: self.width/8 + root.width/20, self.center_y-5
                    size: self.width*3/4, 10
        BoxLayout:
            size_hint: None, None
            size: root.width * 9/10, root.height * 2/10
            pos: root.width /20, root.height * 8/10
            FloatLayout:
                Image:
                    source: root.root_path +'/img/1.png'
                    size_hint: None, None
                    size: 90, 90
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            FloatLayout:
                Image:
                    source: root.root_path +'/img/2_dis.png'
                    size_hint: None, None
                    size: 90, 90
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            FloatLayout:
                Image:
                    source: root.root_path +'/img/3_dis.png'
                    size_hint: None, None
                    size: 90, 90
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            FloatLayout:
                Image:
                    source: root.root_path +'/img/4_dis.png'
                    size_hint: None, None
                    size: 90, 90
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y

        BoxLayout:
            id: box_load
            size_hint: None, None
            size: root.width * 9/10, root.height * 6/10
            pos: root.width /20, root.height * 1.8/10
            spacing: 20
            BoxLayout:
                id: box_load_1
                orientation: "vertical"
                spacing: 10
                Button:
                    background_color: 0, 0.588, 0.533, 1
                    background_normal: ''
                    text: 'Add Receptor'
                    size_hint: None, None
                    size: box_load_1.width, 30
                    on_release: root.show_load_receptor()
                BoxLayout:
                    id: box_list_1
                    size: box_load_1.width, box_load_1.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.9, 0.9, 0.9, 1
                        Line:
                            rectangle: self.x,self.y,self.width,self.height
                    # ListView:
                    #     id: pdb_list_1
                    #     adapter:
                    #         la.ListAdapter(data=[], template='CustomListItem')

            BoxLayout:
                id: box_load_2
                orientation: "vertical"
                spacing: 10
                Button:
                    background_color: 0, 0.588, 0.533, 1
                    background_normal: ''
                    text: 'Add Ligand'
                    size_hint: None, None
                    size: box_load_2.width, 30
                    on_release: root.show_load_ligand()
                BoxLayout:
                    id: box_list_2
                    size: box_load_1.width, box_load_1.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.9, 0.9, 0.9, 1
                        Line:
                            rectangle: self.x,self.y,self.width,self.height