#:kivy 1.9.0
#:import sys sys
#:import lv kivy.uix.listview
#:import la kivy.adapters.listadapter
#:import os os


#---------------------------------------------------#
# Item listview
[LoadListItem@SelectableView+BoxLayout]:
    cbLayout: cb_layout
    size_hint_y: None
    height: 40 + 30*len(ctx.pdbFile.chains) + 1
    BoxLayout:
        id: item_id
        orientation: "vertical"
        size_hint_y: None
        height: 40 + 30*len(ctx.pdbFile.chains) + 1
        # canvas.before:
        #     Color:
        #         rgba: 0, 0.94, 0.94, 1
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size
        BoxLayout:
            size_hint: 1, None
            height: 40
            FloatLayout:
                size_hint_x: None
                width: 30
                padding: 10, 0, 0, 0
                Image:
                    source: 'img/file.png'
                    size: 20, 20
                    allow_stretch: True
                    size_hint: None, None
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y

            BoxLayout:
                size_hint_x: 1.5
                Label:
                    text_size: self.width, None
                    color: 0,0,0,1
                    font_size: '16sp'            
                    text: ctx.text
                    valign: 'middle'
            
            Button:
                size_hint_x: 0.5
                background_color: 1, 1, 1, 0
                on_press: ctx.remove_item(ctx.item_id, ctx.list_id, ctx.pdbFile)
                Image:
                    source: 'img/remove.png'
                    size: 20, 20
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                    allow_stretch: True

        BoxLayout:
            id: cb_layout
            orientation: "vertical"
            # size_hint_y: None
            # height: 50

        BoxLayout:
            size_hint_y: None
            height: 1
            canvas.before:
                Color:
                    rgba: 0.92, 0.92, 0.92, 1
                Rectangle:
                    pos: self.pos
                    size: self.size


<ItemCheckBox>:
    chainName: chain_name
    chainBox: chain_box
    spacing: 20
    size_hint_y: None
    height: 30
    CheckBox:
        id: chain_box
        size_hint_x: None
        width: 50
        active: True
    Label:
        id: chain_name
        text: ''
        color: 0,0,0,1
        font_size: '14sp'
        text_size: self.width, None
        halign: 'left'

[GroupListItem@SelectableView+BoxLayout]:
    cbLayout: cb_layout
    size_hint_y: None 
    height: 30 + 75*int(ctx.number_chain) + 1
    BoxLayout:
        id: item_id
        orientation: "vertical"
        BoxLayout:
            size_hint: 1, None
            height: 30
            FloatLayout:
                size_hint_x: None
                width: 30
                padding: 10, 0, 0, 0
                Image:
                    source: 'img/file.png'
                    size: 20, 20
                    allow_stretch: True
                    size_hint: None, None
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y

            BoxLayout:
                size_hint_x: 1.5
                Label:
                    text_size: self.width, None
                    color: 0,0,0,1
                    font_size: '16sp'            
                    text: ctx.text
                    valign: 'middle'

        BoxLayout:
            id: cb_layout
            orientation: "vertical"
            padding: 25,0,0,0
            # size_hint_y: None
            # height: 50

        BoxLayout:
            size_hint_y: None
            height: 1
            canvas.before:
                Color:
                    rgba: 0.92, 0.92, 0.92, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

<GroupCheckBox>:
    chainName: chain_name
    chainBox: chain_box
    resdiueFrom: resdiue_from
    resdiueTo: resdiue_to

    padding: 0, 5, 10, 5
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            size_hint_y: None
            height: 40  
            CheckBox:
                id: chain_box
                size_hint_x: None
                width: 50
                active: True
            Label:
                id: chain_name
                text: ''
                color: 0,0,0,1
                font_size: '14sp'
                text_size: self.width, None
                halign: 'left'
        BoxLayout:
            size_hint_y: None
            height: 25  
            padding: 50,0,0,0
            Label:
                text: 'Residue: '
                color: 0,0,0,1
                font_size: '14sp'
                text_size: self.width, None
                halign: 'left'
                size_hint_x: root.width * 1/10
            Label:
                text: ' from '
                color: 0,0,0,1
                font_size: '14sp'
                text_size: self.width, None
                halign: 'center'
                size_hint_x: root.width * 1/10
            TextInput:
                id: resdiue_from
                text: ''
                color: 0,0,0,1
                font_size: '14sp'
                text_size: self.width, None
                halign: 'left'
                valign: 'center'
                size_hint_x: root.width * 2/10
                padding_y: 5
            Label:
                text: ' to '
                color: 0,0,0,1
                font_size: '14sp'
                text_size: self.width, None
                halign: 'center'
                size_hint_x: root.width * 1/10
            TextInput:
                id: resdiue_to
                text: ''
                color: 0,0,0,1
                font_size: '14sp'
                text_size: self.width, None
                halign: 'left'
                valign: 'center'
                size_hint_x: root.width * 2/10
                padding_y: 5
            BoxLayout:
                size_hint_x: root.width * 2/10
                

#---------------------------------------------------#
# Screen
<ConfigurationScreen>:
    optimizedButton: optimized_button
    customButton: custom_button

    optimizedTick: optimized_tick
    customTick: custom_tick

    configLayout: config_layout

    canvas.before:
        Color:
            rgba: 0.92, 0.92, 0.92, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size

    FloatLayout:
        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-100, 30
            on_press: root.manager.changeScreen('load')
            Image:
                source: 'img/next.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-200, 30
            on_press: root.manager.changeScreen('receptor')
            Image:
                source: 'img/back.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: 50, 30
            on_press: root.manager.changeScreen('setting')
            Image:
                source: 'img/setting.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True
        BoxLayout:
            size_hint: None, None
            size: root.width * 9/10, root.height * 6/10
            pos: root.width /20, root.height * 2/10
            spacing: 10
            orientation: "vertical"
            Button:
                id: optimized_button
                background_color: 0, 0.588, 0.533, 1
                background_normal: ''
                canvas.after:
                    Color:
                        rgb: 0.9, 0.9, 0.9, 1
                    Line:
                        rectangle: self.x,self.y,self.width,self.height

                size_hint: None, None
                size: self.parent.width, 30
                text: 'Using the optimized configuration available'
                on_press: root.optimizedConfig()
                Image:
                    id: optimized_tick
                    source: 'img/tick.png'
                    size_hint_x: None
                    width: 25
                    center_x: self.parent.center_x - self.parent.width/2 + 40
                    center_y: self.parent.center_y
                    
            Button:
                id: custom_button
                background_color: 0.62, 0.62, 0.62, 1
                background_normal: ''
                canvas.after:
                    Color:
                        rgb: 0.9, 0.9, 0.9, 1
                    Line:
                        rectangle: self.x,self.y,self.width,self.height
                size_hint: None, None
                size: self.parent.width, 30    
                text: 'Using your custom configuration'
                on_press: root.customConfig()
                Image:
                    id: custom_tick
                    source: 'img/tick.png'
                    color: 0,0,0,0
                    size_hint_x: None
                    width: 25
                    center_x: self.parent.center_x - self.parent.width/2 + 40
                    center_y: self.parent.center_y

            ScrollView:
                id: config_layout
                size_hint: None, None
                size: self.parent.width, self.parent.height-80
                canvas.before:
                    Color:
                        rgba: 1,1,1,1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                canvas.after:
                    Color:
                        rgb: 0.9, 0.9, 0.9
                    Line:
                        rectangle: self.x,self.y,self.width,self.height
                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: box_1.height + box_2.height + box_3.height + box_4.height + box_5.height + box_6.height 
                    BoxLayout:
                        id: box_1
                        size_hint_y: None
                        height: 50
                        padding: self.width/8, 0, 20, 0
                        Label:
                            text: ' Use Caver tool'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'
                            size_hint_x: None
                            width: self.parent.width/2
                        CheckBox:
                            size_hint_x: None 
                            width: 30
                            pos: 0,0

                    BoxLayout:
                        id: box_2
                        size_hint_y: None
                        height: 50
                        padding: self.width/8, 0, 20, 0
                        Label:
                            text: ' Use automatic for setting parameter for ligand'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'
                            size_hint_x: None
                            width: self.parent.width/2
                        CheckBox:
                            size_hint_x: None 
                            width: 30
                            pos: 0,0
                            active: True


                    BoxLayout:
                        id: box_3
                        size_hint_y: None
                        height: 50
                        padding: self.width/8, 0, 20, 0
                        Label:
                            text: ' How many times to repeat?'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'
                            size_hint_x: None
                            width: self.parent.width/2
                        TextInput:
                            size_hint: None, 0.6
                            width: 100
                            pos_hint: {'center_y': 0.5}
                            text: '3'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'

                    BoxLayout:
                        id: box_4
                        size_hint_y: None
                        height: 50
                        padding: self.width/8, 0, 20, 0
                        Label:
                            text: ' Do you want to run in backgroud (nohup)?'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'
                            size_hint_x: None
                            width: self.parent.width/2
                        CheckBox:
                            size_hint_x: None 
                            width: 30
                            pos: 0,0

                    BoxLayout:
                        id: box_5
                        size_hint_y: None
                        height: 50
                        padding: self.width/8, 0, 20, 0
                        Label:
                            text: ' Maximum cores for this task'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'
                            size_hint_x: None
                            width: self.parent.width/2
                        TextInput:
                            size_hint: None, 0.6
                            width: 100
                            pos_hint: {'center_y': 0.5}
                            text: '99'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'

                    BoxLayout:
                        id: box_6
                        size_hint_y: None
                        height: 50
                        padding: self.width/8, 0, 20, 0
                        Label:
                            text: ' Auto use GPU to calculate'
                            color: 0,0,0,1
                            disabled_color: 0,0,0,1
                            font_size: '16sp'
                            text_size: self.width, None
                            halign: 'left'
                            valign: 'middle'
                            size_hint_x: None
                            width: self.parent.width/2
                        CheckBox:
                            size_hint_x: None 
                            width: 30
                            pos: 0,0
                            active: True



<ReceptorScreen>:
    receptorList: receptor_list

    canvas.before:
        Color:
            rgba: 0.92, 0.92, 0.92, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size
    FloatLayout:
        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-100, 30
            on_press: root.manager.changeScreen('configuration')
            Image:
                source: 'img/next.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-200, 30
            on_press: root.manager.changeScreen('load')
            Image:
                source: 'img/back.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: 50, 30
            on_press: root.manager.changeScreen('setting')
            Image:
                source: 'img/setting.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        BoxLayout:
            id: receptor_layout
            size_hint: None, None
            size: root.width * 9/10, root.height * 6/10
            pos: root.width /20, root.height * 2/10
            spacing: 10
            orientation: "vertical"
            BoxLayout:
                canvas.before:
                    Color:
                        rgb: 0.62, 0.62, 0.62, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                size_hint: None, None
                size: receptor_layout.width, 30
                padding: 20, 0, 20, 0
                Image:
                    source: 'img/info.png'
                    size_hint_x: None
                    width: 20
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                    allow_stretch: True
                Label:
                    
                    text: 'Please select receptor groups or skip to next step'
                
            BoxLayout:
                BoxLayout:
                    id: receptor_list
                    size: receptor_layout.width, receptor_layout.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1,1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.9, 0.9, 0.9
                        Line:
                            rectangle: self.x,self.y,self.width,self.height



<LoadScreen>:
    boxlist_1: box_list_1    
    boxlist_2: box_list_2

    canvas.before:
        Color:
            rgba: 0.92, 0.92, 0.92, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size

    FloatLayout:
        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: root.width-100, 30
            on_press: root.manager.changeScreen('receptor')
            Image:
                source: 'img/next.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        Button:
            background_color: 1, 1, 1, 0
            size_hint: None, None
            size: 50, 50
            pos: 50, 30
            on_press: root.manager.changeScreen('setting')
            Image:
                source: 'img/setting.png'
                size: 50, 50
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                allow_stretch: True

        BoxLayout:
            id: box_load
            size_hint: None, None
            size: root.width * 9/10, root.height * 6/10
            pos: root.width /20, root.height * 2/10
            spacing: 20
            BoxLayout:
                id: box_load_1
                orientation: "vertical"
                spacing: 10
                Button:
                    background_color: 0, 0.588, 0.533, 1
                    background_normal: ''
                    text: 'Add Receptor'
                    size_hint: None, None
                    size: box_load_1.width, 30
                    on_release: root.show_load_receptor()
                BoxLayout:
                    id: box_list_1
                    size: box_load_1.width, box_load_1.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.9, 0.9, 0.9, 1
                        Line:
                            rectangle: self.x,self.y,self.width,self.height
                    # ListView:
                    #     id: pdb_list_1
                    #     adapter:
                    #         la.ListAdapter(data=[], template='CustomListItem')

            BoxLayout:
                id: box_load_2
                orientation: "vertical"
                spacing: 10
                Button:
                    background_color: 0, 0.588, 0.533, 1
                    background_normal: ''
                    text: 'Add Ligand'
                    size_hint: None, None
                    size: box_load_2.width, 30
                    on_release: root.show_load_ligand()
                BoxLayout:
                    id: box_list_2
                    size: box_load_1.width, box_load_1.height-40
                    canvas.before:
                        Color:
                            rgba: 1,1,1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 0.9, 0.9, 0.9, 1
                        Line:
                            rectangle: self.x,self.y,self.width,self.height

#---------------------------------------------------#
# Dialog
<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            path: os.getcwd()
            multiselect: True

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
